server:
  port: 8080

spring:
  application:
    name: SpringSecurity_JWT
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
jwt:
  expiredAt: 7200000
  secretKey: testjwtsecretkeytestjwtsecretkeytestjwtsecretkey

admin:
  code: iamadmin

springdoc:
  swagger-ui:
    path: /docs